testing sales

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -138,7 +138,7 @@ jobs:
       - name: Run Playwright for Admin tests
         env:
           BASE_URL: 'http://127.0.0.1:8000'
-        run: npx playwright test tests/admin/Catalog/products.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+        run: npx playwright test tests/admin/sales.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
 
       - name: Upload Playwright Videos of tests
         uses: actions/upload-artifact@v4
