divide in parts

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -130,10 +130,55 @@ jobs:
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
 
-      - name: Run Playwright for Shop tests
+      - name: Run Playwright for Shop Auth tests
         env:
           BASE_URL: 'http://127.0.0.1:8000'
-        run: npx playwright test tests/shop --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+        run: npx playwright test tests/shop/auth.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Shop Cart tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/shop/cart.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Shop Mini Cart tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/shop/miniCart.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Shop Cart Page tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/shop/cartPage.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Shop Wishlist tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/shop/wishlist.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Shop Checkout tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/shop/checkout.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Shop Compare tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/shop/compare.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Shop Product, Category tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/shop/cartPage.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Shop Customer tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/shop/customer.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Shop Search tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/shop/search.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
 
       - name: Run Playwright for Admin Auth tests
         env:
