Improved code of shop end and run all tests together

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -10,7 +10,7 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
-    timeout-minutes: 60
+    timeout-minutes: 180
 
     services:
       mysql:
@@ -130,12 +130,22 @@ jobs:
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
 
-      - name: Run Playwright Admin Catalog tests
+      - name: Run Playwright for Shop tests
         env:
           BASE_URL: 'http://127.0.0.1:8000'
-        run: npx playwright test tests/admin/Catalog/products.spec --workers=1 --project=chromium --retries=0 || echo "Some tests failed, but we continue."
+        run: npx playwright test tests/shop --workers=1 --project=chromium --retries=0 || echo "Some tests failed, but we continue."
 
-      - name: Upload Playwright Videos of Admin Catalog tests
+      - name: Run Playwright for Admin tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/admin --workers=1 --project=chromium --retries=0 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Shop customer again tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/shop/customer.spec --workers=1 --project=chromium --retries=0 || echo "Some tests failed, but we continue."
+
+      - name: Upload Playwright Videos of tests
         uses: actions/upload-artifact@v4
         if: always()
         with:
