corection

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -135,10 +135,45 @@ jobs:
           BASE_URL: 'http://127.0.0.1:8000'
         run: npx playwright test tests/shop --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
 
-      - name: Run Playwright for Admin tests
+      - name: Run Playwright for Admin Auth tests
         env:
           BASE_URL: 'http://127.0.0.1:8000'
-        run: npx playwright test tests/admin --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+        run: npx playwright test tests/admin/auth.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Admin Sales tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/admin/sales.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Admin Catalog tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/admin/Catalog --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Admin Customers tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/admin/Customers --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Admin CMS tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/admin/cms.spec --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Admin Marketing tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/admin/Marketing --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Admin Settings tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/admin/Settings --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
+
+      - name: Run Playwright for Admin Configuration tests
+        env:
+          BASE_URL: 'http://127.0.0.1:8000'
+        run: npx playwright test tests/admin/Configuration --workers=1 --project=chromium --retries=1 || echo "Some tests failed, but we continue."
 
       - name: Upload Playwright Videos of tests
         uses: actions/upload-artifact@v4
